name: NugetPush
on:
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: BuildGenerator
      run: dotnet build CommandForgeGenerator/ -c release
    - name: Pack
      run: dotnet pack CommandForgeGenerator/
    - name: Push
      run: dotnet nuget push ./CommandForgeGenerator/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
